export const airports = [
  { city: "Mumbai", airport: "Chhatrapati Shivaji Maharaj International Airport", country: "India", code: "BOM" },
  { city: "Delhi", airport: "Indira Gandhi International Airport", country: "India", code: "DEL" },
  { city: "Bangalore", airport: "Kempegowda International Airport", country: "India", code: "BLR" },
  { city: "Hyderabad", airport: "Rajiv Gandhi International Airport", country: "India", code: "HYD" },
  { city: "Kolkata", airport: "Netaji Subhas Chandra Bose International Airport", country: "India", code: "CCU" },
  { city: "Chennai", airport: "Chennai International Airport", country: "India", code: "MAA" },
  { city: "Dubai", airport: "Dubai International Airport", country: "UAE", code: "DXB" },
  { city: "Singapore", airport: "Changi Airport", country: "Singapore", code: "SIN" },
  { city: "London", airport: "Heathrow Airport", country: "UK", code: "LHR" },
  { city: "New York", airport: "John F. Kennedy International Airport", country: "USA", code: "JFK" },
  
  // --- Added Pakistan Airports (Major International Hubs) ---
  { city: "Karachi", airport: "Jinnah International Airport", country: "Pakistan", code: "KHI" },
  { city: "Islamabad", airport: "Islamabad International Airport", country: "Pakistan", code: "ISB" },
  { city: "Lahore", airport: "Allama Iqbal International Airport", country: "Pakistan", code: "LHE" },
  { city: "Peshawar", airport: "Bacha Khan International Airport", country: "Pakistan", code: "PEW" },
  { city: "Multan", airport: "Multan International Airport", country: "Pakistan", code: "MUX" },
  { city: "Sialkot", airport: "Sialkot International Airport", country: "Pakistan", code: "SKT" },
  { city: "Faisalabad", airport: "Faisalabad International Airport", country: "Pakistan", code: "LYP" },
  { city: "Quetta", airport: "Quetta International Airport", country: "Pakistan", code: "UET" },

  // --- Added Pakistan Regional/Domestic Hubs ---
  { city: "Gwadar", airport: "New Gwadar International Airport", country: "Pakistan", code: "GWD" },
  { city: "Skardu", airport: "Skardu International Airport", country: "Pakistan", code: "KDU" },
  { city: "Gilgit", airport: "Gilgit Airport", country: "Pakistan", code: "GIL" },
  { city: "Rahim Yar Khan", airport: "Shaikh Zayed International Airport", country: "Pakistan", code: "RYK" },
  { city: "Sukkur", airport: "Begum Nusrat Bhutto International Airport", country: "Pakistan", code: "SKZ" },
  { city: "Bahawalpur", airport: "Bahawalpur Airport", country: "Pakistan", code: "BHV" },
  { city: "Dera Ghazi Khan", airport: "Dera Ghazi Khan International Airport", country: "Pakistan", code: "DEA" },

  // --- Previously Added International Hubs (for completeness) ---
  { city: "Atlanta", airport: "Hartsfield-Jackson International Airport", country: "USA", code: "ATL" },
  { city: "Dallas/Fort Worth", airport: "Dallas/Fort Worth International Airport", country: "USA", code: "DFW" },
  { city: "Los Angeles", airport: "Los Angeles International Airport", country: "USA", code: "LAX" },
  { city: "Chicago", airport: "O'Hare International Airport", country: "USA", code: "ORD" },
  { city: "Tokyo", airport: "Tokyo Haneda Airport", country: "Japan", code: "HND" },
  { city: "Istanbul", airport: "Istanbul Airport", country: "Türkiye", code: "IST" },
  { city: "Seoul", airport: "Incheon International Airport", country: "South Korea", code: "ICN" },
  { city: "Paris", airport: "Charles de Gaulle Airport", country: "France", code: "CDG" },
  { city: "Frankfurt", airport: "Frankfurt Airport", country: "Germany", code: "FRA" },
  { city: "Amsterdam", airport: "Schiphol Airport", country: "Netherlands", code: "AMS" },
  { city: "Madrid", airport: "Adolfo Suárez Madrid–Barajas Airport", country: "Spain", code: "MAD" },
  { city: "Doha", airport: "Hamad International Airport", country: "Qatar", code: "DOH" },
  { city: "Kuala Lumpur", airport: "Kuala Lumpur International Airport", country: "Malaysia", code: "KUL" },
  { city: "Bangkok", airport: "Suvarnabhumi Airport", country: "Thailand", code: "BKK" },
  { city: "Hong Kong", airport: "Hong Kong International Airport", country: "Hong Kong", code: "HKG" },
  { city: "Sydney", airport: "Sydney Airport", country: "Australia", code: "SYD" },
  { city: "São Paulo", airport: "Guarulhos International Airport", country: "Brazil", code: "GRU" },
  { city: "Toronto", airport: "Toronto Pearson International Airport", country: "Canada", code: "YYZ" },
  { city: "Mexico City", airport: "Mexico City International Airport", country: "Mexico", code: "MEX" },
  { city: "Cairo", airport: "Cairo International Airport", country: "Egypt", code: "CAI" }
];